# permissions for end users to view displays.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: display-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: crdshortestpath
    app.kubernetes.io/part-of: crdshortestpath
    app.kubernetes.io/managed-by: kustomize
  name: display-viewer-role
rules:
- apiGroups:
  - dijkstra.jinli.io
  resources:
  - displays
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dijkstra.jinli.io
  resources:
  - displays/status
  verbs:
  - get
